project:
  type: website
  output-dir: _site
  render:
    - "en/*.qmd"
    - "es/*.qmd"
    - "pt/*.qmd"

website:
  title: "Intro to Population Data Science"
  description: "Course website â€“ Population Research Center, PSU"
  repo-url: https://github.com/nsacco/psu-popdatasci
  repo-actions: [edit, issue]
  search: true

  navbar:
    right:
      - text: "ğŸŒ English"
        href: en/index.html
      - text: "ğŸ‡ªğŸ‡¸ EspaÃ±ol"
        href: es/index.html
      - text: "ğŸ‡§ğŸ‡· PortuguÃªs"
        href: pt/index.html

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    link-external-newwindow: true
